package com.packetloss.samjho.ui

import com.packetloss.samjho.model.Basis
import com.packetloss.samjho.model.FoodRelation
import com.packetloss.samjho.model.Language
import com.packetloss.samjho.model.MissingField
import com.packetloss.samjho.model.MissingSection
import com.packetloss.samjho.model.TimeOfDay

/**
 * The patient reads the result in the language the consultation happened in, so every label
 * is chosen by the detected language rather than by the phone's locale.
 */
class Strings(private val language: Language) {

    private fun pick(hi: String, en: String) = if (language == Language.HINDI) hi else en

    val diagnosis = pick("डॉक्टर ने क्या बताया", "What the doctor said it is")
    val medicines = pick("दवाइयाँ", "Medicines")
    val avoid = pick("इनसे बचें", "Things to avoid")
    val warnings = pick("खतरे के लक्षण", "Warning signs")
    val followUp = pick("अगली मुलाक़ात", "Next visit")
    val transcript = pick("पूरी बातचीत", "Full transcript")

    val unnamedDosing = pick("खुराक सुनी, पर दवा का नाम साफ़ नहीं", "Dosing heard, medicine name unclear")
    val unnamedDosingHint = pick(
        "यह पंक्ति जैसी सुनी गई वैसी है। किस दवा के लिए है, यह डॉक्टर या दवा वाले से पूछें।",
        "This is the line as heard. Ask your doctor or pharmacist which medicine it is for.",
    )

    val notMentioned = pick("नहीं बताया गया", "Not mentioned")
    val askDoctor = pick(
        "डॉक्टर या दवा वाले से पूछें।",
        "Ask your doctor or pharmacist.",
    )
    val showWords = pick("डॉक्टर के शब्द देखें", "Show the doctor's words")
    val showTranscript = pick("पूरी बातचीत दिखाएँ", "Show full transcript")
    val hideWords = pick("छिपाएँ", "Hide")
    val nothingHere = pick("डॉक्टर ने इस बारे में कुछ नहीं कहा।", "The doctor did not mention this.")

    val share = pick("📤 भेजें", "📤 Share")
    val shareTitle = pick("सार भेजें", "Share the summary")
    val shareAsImage = pick("तस्वीर के रूप में (WhatsApp के लिए सबसे अच्छा)", "As an image (best for WhatsApp)")
    val shareAsPdf = pick("PDF के रूप में", "As a PDF")
    val shareCaption = pick(
        "परामर्श का सार, डॉक्टर के अपने शब्दों से बनाया गया।",
        "Summary of the consultation, generated from the doctor's own words.",
    )
    val shareFailed = pick("सार नहीं बन सका।", "Could not create the summary.")

    fun shareUnconfirmed(n: Int) = pick(
        "$n दवा का नाम अपुष्ट है। भेजे गए सार में उसे \"अपुष्ट\" लिखा जाएगा।",
        if (n == 1) "1 medicine name is not confirmed. It will be marked \"not confirmed\" in the summary."
        else "$n medicine names are not confirmed. They will be marked \"not confirmed\" in the summary.",
    )

    val summaryTitle = pick("परामर्श का सार", "Consultation summary")
    val notConfirmedTitle = pick("अपुष्ट: कृपया जाँच लें", "Not confirmed: please check")
    val notConfirmedAsk = pick(
        "इसे सही दवा मानने से पहले डॉक्टर या दवा वाले से पूछें।",
        "Ask your doctor or pharmacist before treating this as the right medicine.",
    )
    val summaryFooter = pick(
        "यह सार Samjho ने डॉक्टर के अपने शब्दों से बनाया है। यह सिर्फ़ वही दोहराता है जो डॉक्टर ने कहा; यह कोई चिकित्सा सलाह नहीं देता।",
        "Generated by Samjho from the doctor's own words. It only repeats what the doctor said and gives no medical advice.",
    )

    /** Used when the patient confirmed some medicine names from the prescription paper. */
    val summaryFooterWithPrescription = pick(
        "यह सार Samjho ने डॉक्टर के अपने शब्दों और पर्चे के नामों से बनाया है। यह सिर्फ़ वही दोहराता है जो डॉक्टर ने कहा और पर्चे पर लिखा है; यह कोई चिकित्सा सलाह नहीं देता।",
        "Generated by Samjho from the doctor's own words and the medicine names on the prescription. It only repeats what the doctor said and the paper shows, and gives no medical advice.",
    )

    val readAloud = pick("🔊 सुनाएँ", "🔊 Read aloud")
    val stopReading = pick("⏹ रोकें", "⏹ Stop")
    val readIntro = pick("यह वही है जो बातचीत में सुना गया।", "Here is what was heard in the consultation.")

    fun readNotConfirmedUnknown(heard: String) = pick(
        "अपुष्ट: $heard सुना गया। पता नहीं कि यह दवा का नाम है।",
        "Not confirmed: heard as $heard. It is not known whether this is a medicine name.",
    )

    fun readNotConfirmed(heard: String, possibly: String) = pick(
        "अपुष्ट: $heard सुना गया, शायद $possibly।",
        "Not confirmed: heard as $heard, possibly $possibly.",
    )

    val rulesOnly = pick("नियम आधारित", "RULES ONLY")
    val aiChecking = pick("AI जाँच रहा है…", "AI CHECKING…")
    val aiPlusRules = pick("AI + नियम", "AI + RULES")

    val heardAs = pick("सुना गया", "Heard as")

    // ---- details the doctor said in a separate, later sentence
    fun detailName(d: com.packetloss.samjho.model.Detail) = when (d) {
        com.packetloss.samjho.model.Detail.TIMES_PER_DAY -> pick("दिन में कितनी बार", "how many times a day")
        com.packetloss.samjho.model.Detail.TIME_OF_DAY -> pick("दिन का कौन सा समय", "what time of day")
        com.packetloss.samjho.model.Detail.DOSE -> pick("कितनी गोली", "how much each time")
        com.packetloss.samjho.model.Detail.FOOD -> pick("खाने से पहले या बाद", "before or after food")
        com.packetloss.samjho.model.Detail.DURATION -> pick("कितने दिन", "for how many days")
    }
    val saidLater = pick("यह अलग वाक्य में, बाद में कहा गया", "Said in a separate sentence, after the medicine's own")
    val saidLaterShort = pick("अलग वाक्य में कहा गया", "Said in a separate sentence")

    // ---- the prescription: it supplies the names, the doctor's words supply everything else
    val scanPrescription = pick("पर्चा स्कैन करें", "Scan the prescription")
    val scanPrescriptionHint = pick(
        "पर्चे से दवा के सही नाम मिलते हैं। समय, खाने और दिनों के निर्देश वही रहते हैं जो डॉक्टर ने कहे।",
        "The paper gives the exact medicine names. Timings, food and days stay exactly as the doctor said them.",
    )
    val confirmedFromPrescription = pick("पर्चे से पुष्ट", "Confirmed from prescription")
    val fromPrescriptionNotSpoken = pick("पर्चे से, बोला नहीं गया", "From prescription, not spoken")
    val cameraRead = pick("कैमरे ने पढ़ा", "The camera read")

    /** "Confirmed from prescription · heard as “thrombison”", the line under a name the paper settled. */
    fun confirmedFromPrescriptionHeardAs(heard: String?) =
        confirmedFromPrescription + (heard?.let { " · $heardAs “$it”" } ?: "")

    fun readConfirmedFromPrescription(name: String, heard: String?) = pick(
        "$name, पर्चे से पुष्ट${heard?.let { ", $it सुना गया" } ?: ""}",
        "$name, confirmed from the prescription${heard?.let { ", heard as $it" } ?: ""}",
    )

    fun readFromPrescriptionOnly(name: String) = pick(
        "$name, पर्चे से, डॉक्टर ने नहीं बोला।",
        "$name, from the prescription, not mentioned by the doctor.",
    )

    fun paperApplied(named: Int, added: Int) = pick(
        "पर्चा जोड़ा गया: $named नाम पुष्ट, $added दवा जुड़ी।",
        "Prescription applied: $named ${if (named == 1) "name" else "names"} confirmed, $added ${if (added == 1) "medicine" else "medicines"} added.",
    )
    val possibly = pick("शायद", "Possibly")
    val unconfirmed = pick("अपुष्ट", "UNCONFIRMED")
    val isThisAMedicine = pick("क्या यह दवा का नाम है?", "Is this a medicine name?")
    val confirmed = pick("पुष्ट", "CONFIRMED")
    val yes = pick("हाँ", "Yes")
    val no = pick("नहीं", "No")
    val chooseAnother = pick("दूसरा चुनें", "Choose another")
    val chooseTitle = pick("कौन सी दवा?", "Which medicine?")
    val undo = pick("वापस करें", "Undo")
    val dismissed = pick("हटाया गया", "Dismissed")
    val cancel = pick("रद्द करें", "Cancel")
    val noOtherMatch = pick("कोई और मिलता-जुलता नाम नहीं मिला।", "No other close match to offer.")
    val checkName = pick(
        "नाम सुनने में गलती हो सकती है। डॉक्टर के शब्दों से मिलाकर पुष्टि करें।",
        "The name may have been misheard. Check it against the doctor's words, then confirm.",
    )

    fun needConfirming(n: Int) = pick(
        "$n दवा का नाम आपकी पुष्टि माँगता है",
        if (n == 1) "1 medicine name needs your confirmation" else "$n medicine names need your confirmation",
    )

    fun basis(b: Basis, hypothesis: Int?) = when (b) {
        Basis.HEARD -> ""
        Basis.SOUNDS_LIKE -> pick("आवाज़ मिलती है", "Sounds like")
        Basis.ALTERNATE_HEARING -> pick("दूसरी सुनवाई #${(hypothesis ?: 0) + 1}", "Alternative hearing #${(hypothesis ?: 0) + 1}")
        Basis.AI_MATCHED -> pick("AI ने मिलाया", "AI matched")
        Basis.FROM_PRESCRIPTION -> pick("पर्चे से", "From prescription")
    }
    val offline = pick("पूरी तरह ऑफ़लाइन", "Fully offline")
    val disclaimer = pick(
        "Samjho सिर्फ़ वही दोहराता है जो डॉक्टर ने कहा। यह कोई चिकित्सा सलाह नहीं देता।",
        "Samjho only repeats what the doctor said. It never gives medical advice.",
    )

    fun line(index: Int) = pick("पंक्ति ${index + 1}", "Line ${index + 1}")

    fun timesPerDay(n: Int) = pick("दिन में $n बार", if (n == 1) "Once a day" else "$n times a day")

    fun dose(n: Int) = pick("$n गोली", if (n == 1) "1 tablet" else "$n tablets")

    fun durationDays(n: Int) = pick("$n दिन तक", if (n == 1) "For 1 day" else "For $n days")

    fun followUpIn(n: Int) = pick("$n दिन बाद", if (n == 1) "In 1 day" else "In $n days")

    fun timeOfDay(t: TimeOfDay) = when (t) {
        TimeOfDay.MORNING -> pick("सुबह", "Morning")
        TimeOfDay.AFTERNOON -> pick("दोपहर", "Afternoon")
        TimeOfDay.EVENING -> pick("शाम", "Evening")
        TimeOfDay.NIGHT -> pick("रात", "Night")
    }

    fun food(f: FoodRelation) = when (f) {
        FoodRelation.BEFORE_FOOD -> pick("खाने से पहले", "Before food")
        FoodRelation.AFTER_FOOD -> pick("खाने के बाद", "After food")
        FoodRelation.EMPTY_STOMACH -> pick("खाली पेट", "Empty stomach")
        FoodRelation.WITH_FOOD -> pick("खाने के साथ", "With food")
    }

    fun missing(f: MissingField) = when (f) {
        MissingField.TIMES_PER_DAY -> pick("दिन में कितनी बार", "how many times a day")
        MissingField.TIME_OF_DAY -> pick("किस समय", "what time of day")
        MissingField.FOOD_RELATION -> pick("खाने से पहले या बाद", "before or after food")
        MissingField.DURATION -> pick("कितने दिन तक", "for how many days")
    }

    fun missingSection(s: MissingSection) = when (s) {
        MissingSection.MEDICINES -> pick("कोई दवा", "any medicine")
        MissingSection.DIAGNOSIS -> pick("बीमारी का नाम", "what the problem is")
        MissingSection.AVOID -> pick("परहेज़", "anything to avoid")
        MissingSection.WARNINGS -> pick("खतरे के लक्षण", "warning signs")
        MissingSection.FOLLOW_UP -> pick("अगली मुलाक़ात", "a next visit")
    }
}
