package com.packetloss.samjho.ui

import com.packetloss.samjho.AiState
import com.packetloss.samjho.llm.LlmStatus
import com.packetloss.samjho.llm.LlmStatusText
import com.packetloss.samjho.model.Basis
import com.packetloss.samjho.model.FoodRelation
import com.packetloss.samjho.model.Language
import com.packetloss.samjho.model.MissingField
import com.packetloss.samjho.model.MissingSection
import com.packetloss.samjho.model.TimeOfDay

/**
 * The patient reads the result in the language the consultation happened in, so every label
 * is chosen by the detected language rather than by the phone's locale.
 */
class Strings(private val language: Language) {

    private fun pick(hi: String, en: String) = if (language == Language.HINDI) hi else en

    val diagnosis = pick("डॉक्टर ने क्या बताया", "What the doctor said it is")
    val medicines = pick("दवाइयाँ", "Medicines")
    val avoid = pick("इनसे बचें", "Things to avoid")
    val warnings = pick("खतरे के लक्षण", "Warning signs")
    val followUp = pick("अगली मुलाक़ात", "Next visit")
    val transcript = pick("पूरी बातचीत", "Full transcript")

    val unnamedDosing = pick("खुराक सुनी, पर दवा का नाम साफ़ नहीं", "Dosing heard, medicine name unclear")
    val unnamedDosingHint = pick(
        "यह पंक्ति जैसी सुनी गई वैसी है। किस दवा के लिए है, यह डॉक्टर या दवा वाले से पूछें।",
        "This is the line as heard. Ask your doctor or pharmacist which medicine it is for.",
    )

    val notMentioned = pick("नहीं बताया गया", "Not mentioned")
    val askDoctor = pick(
        "डॉक्टर या दवा वाले से पूछें।",
        "Ask your doctor or pharmacist.",
    )
    val showWords = pick("डॉक्टर के शब्द देखें", "Show the doctor's words")
    val showTranscript = pick("पूरी बातचीत दिखाएँ", "Show full transcript")
    val hideWords = pick("छिपाएँ", "Hide")
    val nothingHere = pick("डॉक्टर ने इस बारे में कुछ नहीं कहा।", "The doctor did not mention this.")

    val share = pick("📤 भेजें", "📤 Share")
    val shareTitle = pick("सार भेजें", "Share the summary")
    val shareAsImage = pick("तस्वीर के रूप में (WhatsApp के लिए सबसे अच्छा)", "As an image (best for WhatsApp)")
    val shareAsPdf = pick("PDF के रूप में", "As a PDF")
    val shareCaption = pick(
        "परामर्श का सार, डॉक्टर के अपने शब्दों से बनाया गया।",
        "Summary of the consultation, generated from the doctor's own words.",
    )
    val shareFailed = pick("सार नहीं बन सका।", "Could not create the summary.")

    fun shareUnconfirmed(n: Int) = pick(
        "$n दवा का नाम अपुष्ट है। भेजे गए सार में उसे \"अपुष्ट\" लिखा जाएगा।",
        if (n == 1) "1 medicine name is not confirmed. It will be marked \"not confirmed\" in the summary."
        else "$n medicine names are not confirmed. They will be marked \"not confirmed\" in the summary.",
    )

    val summaryTitle = pick("परामर्श का सार", "Consultation summary")
    val notConfirmedTitle = pick("अपुष्ट: कृपया जाँच लें", "Not confirmed: please check")
    val notConfirmedAsk = pick(
        "इसे सही दवा मानने से पहले डॉक्टर या दवा वाले से पूछें।",
        "Ask your doctor or pharmacist before treating this as the right medicine.",
    )
    val summaryFooter = pick(
        "यह सार Samjho ने डॉक्टर के अपने शब्दों से बनाया है। यह सिर्फ़ वही दोहराता है जो डॉक्टर ने कहा; यह कोई चिकित्सा सलाह नहीं देता।",
        "Generated by Samjho from the doctor's own words. It only repeats what the doctor said and gives no medical advice.",
    )

    /** Used when the patient confirmed some medicine names from the prescription paper. */
    val summaryFooterWithPrescription = pick(
        "यह सार Samjho ने डॉक्टर के अपने शब्दों और पर्चे के नामों से बनाया है। यह सिर्फ़ वही दोहराता है जो डॉक्टर ने कहा और पर्चे पर लिखा है; यह कोई चिकित्सा सलाह नहीं देता।",
        "Generated by Samjho from the doctor's own words and the medicine names on the prescription. It only repeats what the doctor said and the paper shows, and gives no medical advice.",
    )

    val readAloud = pick("🔊 सुनाएँ", "🔊 Read aloud")
    val stopReading = pick("⏹ रोकें", "⏹ Stop")
    val readIntro = pick("यह वही है जो बातचीत में सुना गया।", "Here is what was heard in the consultation.")

    fun readNotConfirmedUnknown(heard: String) = pick(
        "अपुष्ट: $heard सुना गया। पता नहीं कि यह दवा का नाम है।",
        "Not confirmed: heard as $heard. It is not known whether this is a medicine name.",
    )

    fun readNotConfirmed(heard: String, possibly: String) = pick(
        "अपुष्ट: $heard सुना गया, शायद $possibly।",
        "Not confirmed: heard as $heard, possibly $possibly.",
    )

    val rulesOnly = pick("नियम आधारित", "RULES ONLY")
    val aiChecking = pick("AI जाँच रहा है…", "AI CHECKING…")
    val aiPlusRules = pick("AI + नियम", "AI + RULES")

    val heardAs = pick("सुना गया", "Heard as")

    // ---- details the doctor said in a separate, later sentence
    fun detailName(d: com.packetloss.samjho.model.Detail) = when (d) {
        com.packetloss.samjho.model.Detail.TIMES_PER_DAY -> pick("दिन में कितनी बार", "how many times a day")
        com.packetloss.samjho.model.Detail.TIME_OF_DAY -> pick("दिन का कौन सा समय", "what time of day")
        com.packetloss.samjho.model.Detail.DOSE -> pick("कितनी गोली", "how much each time")
        com.packetloss.samjho.model.Detail.FOOD -> pick("खाने से पहले या बाद", "before or after food")
        com.packetloss.samjho.model.Detail.DURATION -> pick("कितने दिन", "for how many days")
    }
    val saidLater = pick("यह अलग वाक्य में, बाद में कहा गया", "Said in a separate sentence, after the medicine's own")
    val saidLaterShort = pick("अलग वाक्य में कहा गया", "Said in a separate sentence")

    // ---- the prescription: it supplies the names, the doctor's words supply everything else
    val scanPrescription = pick("पर्चा स्कैन करें", "Scan the prescription")
    val scanPrescriptionHint = pick(
        "पर्चे से दवा के सही नाम मिलते हैं। समय, खाने और दिनों के निर्देश वही रहते हैं जो डॉक्टर ने कहे।",
        "The paper gives the exact medicine names. Timings, food and days stay exactly as the doctor said them.",
    )
    val confirmedFromPrescription = pick("पर्चे से पुष्ट", "Confirmed from prescription")
    val fromPrescriptionNotSpoken = pick("पर्चे से, बोला नहीं गया", "From prescription, not spoken")
    val cameraRead = pick("कैमरे ने पढ़ा", "The camera read")

    /** "Confirmed from prescription · heard as “thrombison”", the line under a name the paper settled. */
    fun confirmedFromPrescriptionHeardAs(heard: String?) =
        confirmedFromPrescription + (heard?.let { " · $heardAs “$it”" } ?: "")

    fun readConfirmedFromPrescription(name: String, heard: String?) = pick(
        "$name, पर्चे से पुष्ट${heard?.let { ", $it सुना गया" } ?: ""}",
        "$name, confirmed from the prescription${heard?.let { ", heard as $it" } ?: ""}",
    )

    fun readFromPrescriptionOnly(name: String) = pick(
        "$name, पर्चे से, डॉक्टर ने नहीं बोला।",
        "$name, from the prescription, not mentioned by the doctor.",
    )

    fun paperApplied(named: Int, added: Int) = pick(
        "पर्चा जोड़ा गया: $named नाम पुष्ट, $added दवा जुड़ी।",
        "Prescription applied: $named ${if (named == 1) "name" else "names"} confirmed, $added ${if (added == 1) "medicine" else "medicines"} added.",
    )
    val possibly = pick("शायद", "Possibly")
    val unconfirmed = pick("अपुष्ट", "UNCONFIRMED")
    val isThisAMedicine = pick("क्या यह दवा का नाम है?", "Is this a medicine name?")
    val confirmed = pick("पुष्ट", "CONFIRMED")
    val yes = pick("हाँ", "Yes")
    val no = pick("नहीं", "No")
    val chooseAnother = pick("दूसरा चुनें", "Choose another")
    val chooseTitle = pick("कौन सी दवा?", "Which medicine?")
    val undo = pick("वापस करें", "Undo")
    val dismissed = pick("हटाया गया", "Dismissed")
    val cancel = pick("रद्द करें", "Cancel")
    val noOtherMatch = pick("कोई और मिलता-जुलता नाम नहीं मिला।", "No other close match to offer.")
    val checkName = pick(
        "नाम सुनने में गलती हो सकती है। डॉक्टर के शब्दों से मिलाकर पुष्टि करें।",
        "The name may have been misheard. Check it against the doctor's words, then confirm.",
    )

    fun needConfirming(n: Int) = pick(
        "$n दवा का नाम आपकी पुष्टि माँगता है",
        if (n == 1) "1 medicine name needs your confirmation" else "$n medicine names need your confirmation",
    )

    fun basis(b: Basis, hypothesis: Int?) = when (b) {
        Basis.HEARD -> ""
        Basis.SOUNDS_LIKE -> pick("आवाज़ मिलती है", "Sounds like")
        Basis.ALTERNATE_HEARING -> pick("दूसरी सुनवाई #${(hypothesis ?: 0) + 1}", "Alternative hearing #${(hypothesis ?: 0) + 1}")
        Basis.AI_MATCHED -> pick("AI ने मिलाया", "AI matched")
        Basis.FROM_PRESCRIPTION -> pick("पर्चे से", "From prescription")
    }
    val offline = pick("पूरी तरह ऑफ़लाइन", "Fully offline")
    val disclaimer = pick(
        "Samjho सिर्फ़ वही दोहराता है जो डॉक्टर ने कहा। यह कोई चिकित्सा सलाह नहीं देता।",
        "Samjho only repeats what the doctor said. It never gives medical advice.",
    )

    fun line(index: Int) = pick("पंक्ति ${index + 1}", "Line ${index + 1}")

    // ---- the medicine card: one plain sentence instead of labelled rows
    /**
     * "1 tablet, 3 times a day, after food, for 5 days": only what the doctor said, in the order a person would say it.
     * Null when none of it was said (the card then shows only what was "Not mentioned").
     */
    fun sentence(m: com.packetloss.samjho.model.Medicine): String? {
        val parts = buildList {
            m.doseCount?.let { add(dose(it)) }
            m.timesPerDay?.let { add(pick("दिन में $it बार", if (it == 1) "once a day" else "$it times a day")) }
            if (m.timesOfDay.isNotEmpty()) add(m.timesOfDay.joinToString(pick(", ", " and ")) { plainTimeOfDay(it) })
            m.foodRelation?.let { add(plainFood(it)) }
            m.durationDays?.let { add(pick("$it दिन तक", if (it == 1) "for 1 day" else "for $it days")) }
        }
        if (parts.isEmpty()) return null
        return parts.joinToString(", ").replaceFirstChar { it.uppercase() }
    }

    private fun plainTimeOfDay(t: TimeOfDay) = when (t) {
        TimeOfDay.MORNING -> pick("सुबह", "in the morning")
        TimeOfDay.AFTERNOON -> pick("दोपहर", "in the afternoon")
        TimeOfDay.EVENING -> pick("शाम", "in the evening")
        TimeOfDay.NIGHT -> pick("रात", "at night")
    }

    private fun plainFood(f: FoodRelation) = when (f) {
        FoodRelation.BEFORE_FOOD -> pick("खाने से पहले", "before food")
        FoodRelation.AFTER_FOOD -> pick("खाने के बाद", "after food")
        FoodRelation.EMPTY_STOMACH -> pick("खाली पेट", "on an empty stomach")
        FoodRelation.WITH_FOOD -> pick("खाने के साथ", "with food")
    }

    // ---- the on-device AI indicator
    /**
     * The one small line that says whether the AI model is really running. It says "on device" only while the model is
     * loaded and answering; loading, failed, missing or not started all say something else, so the app never claims AI
     * while it is off.
     */
    fun aiIndicator(llm: LlmStatus, ai: AiState): AiIndicator = when {
        ai is AiState.Unavailable || llm is LlmStatus.Failed || llm === LlmStatus.Idle ->
            AiIndicator(pick("AI बंद · सिर्फ़ नियम", "AI off · rules only"), active = false)
        llm is LlmStatus.Loading ->
            AiIndicator(pick("AI मॉडल तैयार हो रहा है…", "AI model loading…"), active = false)
        llm is LlmStatus.Ready -> AiIndicator(
            pick("AI फ़ोन पर · ", "AI on device · ") + LlmStatusText.backendLine(llm) +
                if (ai is AiState.Checking) pick(" · जाँच रहा है…", " · checking…") else "",
            active = true,
        )
        else -> AiIndicator(pick("AI बंद · सिर्फ़ नियम", "AI off · rules only"), active = false)
    }

    // ---- medicine reminders
    val reminderChannel = pick("दवा की याद", "Medicine reminders")
    val reminderTitle = pick("दवा का समय", "Time for your medicine")

    /** "Paracetamol, 1 tablet, after food": the name and only what the doctor said about how to take it. */
    fun reminderLine(name: String, doseCount: Int?, food: FoodRelation?): String =
        listOfNotNull(name, howToTake(doseCount, food)).joinToString(", ")

    /** "1 tablet, after food": the dose and the food instruction, if the doctor gave them. */
    fun howToTake(doseCount: Int?, food: FoodRelation?): String? =
        listOfNotNull(doseCount?.let { dose(it) }, food?.let { plainFood(it) }).joinToString(", ").ifEmpty { null }

    val setReminders = pick("⏰  याद दिलाना चालू करें", "⏰  Set reminders")
    val setRemindersHint = pick(
        "जिन दवाओं का समय डॉक्टर ने बताया, उनके लिए रोज़ याद दिलाएगा।",
        "A daily reminder for each medicine the doctor gave a time of day for.",
    )
    val reminders = pick("दवा की याद", "Reminders")
    val viewReminders = pick("याद दिलाने वाले देखें", "See reminders")
    val noReminders = pick("कोई याद दिलाना चालू नहीं है।", "No reminders are set.")
    val cancelAll = pick("सब रद्द करें", "Cancel all")
    val openSummary = pick("सार खोलें", "Open the summary")
    val untilCancelled = pick("जब तक आप रद्द न करें", "Until you cancel")
    val notificationsOff = pick(
        "इस ऐप की सूचनाएँ बंद हैं, इसलिए याद दिलाना दिखेगा नहीं। सेटिंग में सूचनाएँ चालू करें।",
        "Notifications are off for Samjho, so reminders will not show. Turn them on in Settings.",
    )
    val openSettings = pick("सेटिंग खोलें", "Open Settings")

    fun remindersSet(n: Int) = pick(
        "✓ $n याद दिलाना चालू हुआ",
        "✓ $n ${if (n == 1) "reminder" else "reminders"} set",
    )

    fun noTimeGiven(name: String) = pick(
        "$name: डॉक्टर ने दिन का समय नहीं बताया, इसलिए याद नहीं दिलाई जाएगी।",
        "$name: the doctor did not say a time of day, so there is no reminder.",
    )

    fun notConfirmedNoReminder(name: String) = pick(
        "$name: नाम की पुष्टि होनी बाकी है, इसलिए याद नहीं दिलाई जाएगी।",
        "$name: the name is not confirmed yet, so there is no reminder.",
    )

    val nothingToRemind = pick("किसी दवा का समय डॉक्टर ने नहीं बताया, इसलिए कोई याद नहीं लगी।", "The doctor gave no time of day for any medicine, so no reminder was set.")

    /** "8:00 am · Morning" / "सुबह 8:00". */
    fun reminderTime(slot: TimeOfDay, hour: Int): String {
        val h12 = if (hour % 12 == 0) 12 else hour % 12
        return pick("${timeOfDay(slot)} $h12:00", "$h12:00 ${if (hour < 12) "am" else "pm"} · ${timeOfDay(slot)}")
    }

    fun daysLeft(n: Int) = pick("$n दिन बाकी", if (n == 1) "1 day left" else "$n days left")

    // ---- toggle and navigation
    val back = pick("← वापस", "← Back")
    val close = pick("बंद करें", "Close")
    val stillChecking = pick("कुछ अस्पष्ट शब्द जाँचे जा रहे हैं…", "Checking a few unclear words…")
    val hideDoctorWords = pick("डॉक्टर के शब्द छिपाएँ", "Hide the doctor's words")
    val doctorSaid = pick("डॉक्टर ने कहा", "The doctor said")
    val diagnosisSaid = pick("डॉक्टर ने क्या बताया", "What the doctor said it is")

    // ---- home
    val tagline = pick("डॉक्टर ने जो कहा, आपकी भाषा में।", "What the doctor said, explained back to you.")
    val recordConsultation = pick("🎙  बातचीत रिकॉर्ड करें", "🎙  Record consultation")
    val consent = pick("डॉक्टर ने रिकॉर्डिंग की अनुमति दी है", "The doctor has agreed to be recorded")
    val consentNeeded = pick("पहले डॉक्टर की अनुमति पर निशान लगाएँ।", "Tick the box first: the doctor must agree to be recorded.")
    val micNeeded = pick("रिकॉर्ड करने के लिए माइक की अनुमति चाहिए।", "Microphone permission is needed to record.")
    val scanShort = pick("📷  पर्चा स्कैन करें", "📷  Scan the prescription")
    val demoHeading = pick("नमूना बातचीत देखें", "Try a demo consultation")
    val speechOptions = pick("बोली पहचान चुनें", "Speech recogniser")

    /** The one quiet line on the home screen: is speech ready, is the AI model ready. Nothing more. */
    fun readiness(speechReady: Boolean, ai: com.packetloss.samjho.llm.LlmStatus): String {
        val aiReady = ai is com.packetloss.samjho.llm.LlmStatus.Ready
        val aiLoading = ai is com.packetloss.samjho.llm.LlmStatus.Loading
        return when {
            speechReady && aiReady -> pick("ऑफ़लाइन बोली और AI मॉडल तैयार हैं", "Offline speech and AI model ready")
            speechReady && aiLoading -> pick("ऑफ़लाइन बोली तैयार है · AI मॉडल तैयार हो रहा है", "Offline speech ready · AI model getting ready")
            speechReady -> pick("ऑफ़लाइन बोली तैयार है · AI मॉडल उपलब्ध नहीं", "Offline speech ready · AI model not available")
            aiReady -> pick("इस भाषा के लिए बोली तैयार नहीं · AI मॉडल तैयार है", "Speech not ready for this language · AI model ready")
            else -> pick("इस भाषा के लिए बोली तैयार नहीं", "Speech not ready for this language")
        }
    }

    // ---- recording
    val listening = pick("सुन रहा है…", "Listening…")
    val micOn = pick("माइक चालू है", "Microphone is on")
    val notGuaranteedOffline = pick("यह पूरी तरह ऑफ़लाइन होगा, इसकी गारंटी नहीं है।", "This is not guaranteed to stay offline.")
    val gettingSpeechReady = pick(
        "बोली पहचान तैयार हो रही है (पहली बार कुछ सेकंड लगते हैं)…",
        "Getting speech recognition ready (a few seconds the first time)…",
    )
    val stopAndExplain = pick("रोकें और समझें", "Stop and explain")

    // ---- prescription scan
    val scanTitle = pick("पर्चा स्कैन", "Prescription scan")
    val cameraNeeded = pick("स्कैन के लिए कैमरे की अनुमति चाहिए", "The camera is needed to scan")
    val cameraRefused = pick(
        "कैमरे की अनुमति नहीं मिली। आप अनुमति दे सकते हैं, या कैमरे के बिना सूची से दवा चुन सकते हैं।",
        "Camera permission was refused. You can allow it, or pick your medicine from the list without the camera.",
    )
    val cameraPrivacy = pick(
        "फ़ोटो इसी फ़ोन पर पढ़ी जाती है। वह सेव नहीं होती और फ़ोन से बाहर नहीं जाती।",
        "The photo is read on this phone. It is not saved and never leaves the phone.",
    )
    val allowCamera = pick("कैमरा चालू करें", "Allow camera")
    val fillFrame = pick("पर्चे को फ्रेम में रखें", "Fill the frame with the prescription")
    val readingPrescription = pick("पर्चा पढ़ रहे हैं…", "Reading the prescription…")
    val onThisPhoneOnly = pick("सिर्फ़ इसी फ़ोन पर।", "On this phone only.")
    val scanFailed = pick("स्कैन नहीं हो सका", "The scan did not work")
    val stillPickFromList = pick("आप फिर भी सूची से दवा चुन सकते हैं।", "You can still pick your medicine from the list.")
    val tryCameraAgain = pick("कैमरे से फिर कोशिश करें", "Try the camera again")
    val pickFromList = pick("सूची से दवा चुनें", "Pick a medicine from the list")
    val nothingMatched = pick("पन्ने पर सूची की कोई दवा नहीं मिली।", "Nothing on the page matched a medicine in the list.")
    val nothingMatchedHint = pick(
        "हाथ की लिखावट या धुंधली फ़ोटो में ऐसा होता है। नीचे सूची से अपनी दवा चुनें, या फिर से स्कैन करें।",
        "This is normal for handwriting or a blurry photo. Pick your medicine from the list below, or scan again.",
    )

    fun foundPossible(n: Int) = pick(
        "कैमरे को $n संभावित दवा मिली। हर एक को अपने पर्चे से मिलाएँ, फिर पुष्टि करें।",
        "The camera found $n possible ${if (n == 1) "medicine" else "medicines"}. Check each against your prescription, then confirm.",
    )

    fun useConfirmed(n: Int) = pick("सार में जोड़ें: $n पुष्ट", "Use $n confirmed in the summary")
    val confirmToUse = pick("सार में जोड़ने के लिए किसी दवा की पुष्टि करें", "Confirm a medicine to use it in the summary")
    val didntFind = pick("दवा नहीं मिली?", "Didn't find your medicine?")
    val scanAgain = pick("फिर से स्कैन करें", "Scan again")
    val showCameraRead = pick("कैमरे ने क्या पढ़ा, दिखाएँ", "Show what the camera read")
    val nothingRead = pick("फ़ोटो से कुछ नहीं पढ़ा गया।", "Nothing was read from the photo.")
    val scanDisclaimer = pick(
        "Samjho सिर्फ़ वही दिखाता है जो कैमरे ने पढ़ा और जो नाम आप चुनते हैं। यह कोई चिकित्सा सलाह नहीं देता। फ़ोटो इसी फ़ोन पर रहती है।",
        "Samjho only shows what the camera read and the names you choose. It gives no medical advice. The photo stays on this phone.",
    )
    val confirmButton = pick("पुष्टि करें", "Confirm")
    val rejectButton = pick("हटाएँ", "Reject")
    val checkAgainstPrescription = pick("पुष्टि से पहले इसे अपने पर्चे से मिलाएँ।", "Check this against your prescription before confirming.")
    val confirmedAs = pick("पुष्ट नाम", "Confirmed as")
    val aiMatched = pick("AI ने मिलाया", "AI matched")
    val pickedByYou = pick("आपने चुना", "Picked by you")
    val pickTitle = pick("अपनी दवा चुनें", "Pick your medicine")
    val whichMedicine = pick("कौन सी दवा है?", "Which medicine is it?")
    val typeFewLetters = pick("कुछ अक्षर लिखें, जैसे para", "Type a few letters, e.g. para")
    val noNameInList = pick("इस नाम की कोई दवा सूची में नहीं है। कम अक्षर लिखकर देखें।", "No medicine with that name is in the list. Try fewer letters.")
    val added = pick("✓ जुड़ी", "✓ added")

    fun timesPerDay(n: Int) = pick("दिन में $n बार", if (n == 1) "Once a day" else "$n times a day")

    fun dose(n: Int) = pick("$n गोली", if (n == 1) "1 tablet" else "$n tablets")

    fun durationDays(n: Int) = pick("$n दिन तक", if (n == 1) "For 1 day" else "For $n days")

    fun followUpIn(n: Int) = pick("$n दिन बाद", if (n == 1) "In 1 day" else "In $n days")

    fun timeOfDay(t: TimeOfDay) = when (t) {
        TimeOfDay.MORNING -> pick("सुबह", "Morning")
        TimeOfDay.AFTERNOON -> pick("दोपहर", "Afternoon")
        TimeOfDay.EVENING -> pick("शाम", "Evening")
        TimeOfDay.NIGHT -> pick("रात", "Night")
    }

    fun food(f: FoodRelation) = when (f) {
        FoodRelation.BEFORE_FOOD -> pick("खाने से पहले", "Before food")
        FoodRelation.AFTER_FOOD -> pick("खाने के बाद", "After food")
        FoodRelation.EMPTY_STOMACH -> pick("खाली पेट", "Empty stomach")
        FoodRelation.WITH_FOOD -> pick("खाने के साथ", "With food")
    }

    fun missing(f: MissingField) = when (f) {
        MissingField.TIMES_PER_DAY -> pick("दिन में कितनी बार", "how many times a day")
        MissingField.TIME_OF_DAY -> pick("किस समय", "what time of day")
        MissingField.FOOD_RELATION -> pick("खाने से पहले या बाद", "before or after food")
        MissingField.DURATION -> pick("कितने दिन तक", "for how many days")
    }

    fun missingSection(s: MissingSection) = when (s) {
        MissingSection.MEDICINES -> pick("कोई दवा", "any medicine")
        MissingSection.DIAGNOSIS -> pick("बीमारी का नाम", "what the problem is")
        MissingSection.AVOID -> pick("परहेज़", "anything to avoid")
        MissingSection.WARNINGS -> pick("खतरे के लक्षण", "warning signs")
        MissingSection.FOLLOW_UP -> pick("अगली मुलाक़ात", "a next visit")
    }
}

/** [active] is true only while the model is loaded and answering. */
data class AiIndicator(val text: String, val active: Boolean)
